name: Deploy CloudFormation Template

on:
  push:
    branches:
      - main  # Du kannst den Branch nach Bedarf anpassen

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout des Codes
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Set AWS credentials using session token
      - name: Configure AWS Access
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # 3. CloudFormation Stack deployen
      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file EC2_Deployment_Template.yaml \
            --stack-name VPCDeploymentStack \
            --capabilities CAPABILITY_NAMED_IAM
